-- ============================================================
-- TajWater Custom Payment Links Table
-- Run this in your Supabase SQL Editor
-- ============================================================

create table if not exists public.payment_links (
  id             text primary key,                          -- e.g. 'TW-A3X9'
  description    text                    not null,
  amount         numeric(10,2)           not null,
  currency       text                    not null default 'CAD',
  customer_name  text,
  customer_phone text,
  customer_email text,
  internal_note  text,
  status         text                    not null default 'pending'
                   check (status in ('pending', 'paid')),
  square_payment_id text,
  line_items     jsonb,
  created_at     timestamptz             not null default now(),
  paid_at        timestamptz,
  created_by     text
);

comment on table public.payment_links is
  'Custom one-off payment links generated by TajWater admins.';

-- Enable Row Level Security
alter table public.payment_links enable row level security;

-- Anonymous clients (public pay portal) can SELECT
create policy "anon_select_payment_links"
  on public.payment_links
  for select
  to anon
  using (true);

-- Service role (API routes using createServerClient) bypasses RLS automatically.
-- No additional policies needed for service role.

-- Index for fast status lookups in admin list view
create index if not exists idx_payment_links_status
  on public.payment_links (status, created_at desc);
